options:
  verbose:
    type: string
    default: "true"
    description: Set verbose logging.  Can be set to true or false
  root_secret:
    type: string
    default: "toto"
    description: Secret key used by API clients to manage users.  Please change it in production.
  nodes_secret:
    type: string
    default: "abcd"
    description: Secret key used by workers/nodes to callback API when they finish their job.  Please change it in production.
  repositories_user:
    type: string
    default: "oscied"
    description: OSCIED charms repositories client username.
  repositories_pass:
    type: string
    default: ""
    description: OSCIED charms repositories client password.
  oscied_repository:
    type: string
    default: "https://github.com/EBU-TI/OSCIED/charms"
    description: OSCIED charms will be checked out locally under ~/charms/(release).
  mongo_admin_password:
    type: string
    default: "Mongo_admin_1234"
    description: Database administrator password.
  mongo_nodes_password:
    type: string
    default: "Mongo_user_1234"
    description: Database nodes password.
  rabbit_password:
    type: string
    default: "Alice_in_wonderland"
    description: Messaging queue user's password.  This secret is then forwared by the coordinator to managed units (transform, publish).
  storage_address:
    type: string
    default: ""
    description: Shared storage hostname / IP address (see interface mount of nfs charm).  The 'storage' options override and disable storage relation.
  storage_nat_address:
    type: string
    default: ""
    description: Shared storage reacheable (public) address e.g. when storage is behind a NAT/FW.
  storage_fstype:
    type: string
    default: ""
    description: Shared storage filesystem type (e.g. nfs)
  storage_mountpoint:
    type: string
    default: ""
    description: Shared storage mountpoint (e.g. for nfs - /srv/data)
  storage_options:
    type: string
    default: ""
    description: Shared storage options (e.g. for nfs - rw,sync,no_subtree_check)
