language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - travis_retry sudo apt-get install ffmpeg screen
  - cd library
  - travis_retry sh setup.sh
script:
  - sudo python setup.py test
matrix:
  allow_failures:
    - python: "2.6"
    - python: "3.2"
    - python: "3.3"
