oscied-orchestra:
  verbose: "false"
  cleanup: "false"
  root_secret: "t7LY8ZgQfv5Sb0Un"
  node_secret: "ilKkBr0xBC6gzumz"
  repositories_user: "oscied"
  repositories_pass: "aAvUFKMtvI35ZGUy"
  oscied_repository: "https://github.com/ebu/OSCIED/charms"
  mongo_admin_password: "zuT4NaKJRllxkWTA"
  mongo_node_password: "p09BPRYTaqKswzjT"
  rabbit_password: "Pa0bQ2XFFftAoxlU"
  email_server: ""
  email_tls: "true"
  email_address: "someone@oscied.org"
  email_username: "someone"
  email_password: "1234"
  storage_address: "192.168.0.9"
  storage_nat_address: ""
  storage_fstype: "glusterfs"
  storage_mountpoint: "medias_volume_0"
  storage_options: ""
oscied-publisher1:
  verbose: "false"
  cleanup: "false"
  concurrency: 2
  rabbit_queues: "publisher_private"
  mod_streaming: "false"
  max_upload_size: 4294967296
  max_execution_time: 180
  max_input_time: 600
  mongo_connection: "mongodb://nodes:p09BPRYTaqKswzjT@192.168.0.5:27017/celery"
  rabbit_connection: "amqp://nodes:Pa0bQ2XFFftAoxlU@192.168.0.5:5672/celery"
  api_nat_socket: ""
  storage_address: ""
  storage_nat_address: ""
  storage_fstype: ""
  storage_mountpoint: ""
  storage_options: ""
oscied-publisher2:
  verbose: "false"
  cleanup: "false"
  concurrency: 2
  rabbit_queues: "publisher_private"
  mod_streaming: "false"
  max_upload_size: 4294967296
  max_execution_time: 180
  max_input_time: 600
  mongo_connection: "mongodb://nodes:p09BPRYTaqKswzjT@192.168.0.5:27017/celery"
  rabbit_connection: "amqp://nodes:Pa0bQ2XFFftAoxlU@192.168.0.5:5672/celery"
  api_nat_socket: ""
  storage_address: ""
  storage_nat_address: ""
  storage_fstype: ""
  storage_mountpoint: ""
  storage_options: ""
oscied-storage:
  verbose: "false"
  cleanup: "false"
  allowed_ips: "*"
  replica_count: 1
  bricks_root_path: "/mnt"
oscied-transform1:
  verbose: "false"
  cleanup: "false"
  concurrency: 6
  rabbit_queues: "transform_private"
  mongo_connection: "mongodb://nodes:p09BPRYTaqKswzjT@192.168.0.5:27017/celery"
  rabbit_connection: "amqp://nodes:Pa0bQ2XFFftAoxlU@192.168.0.5:5672/celery"
  api_nat_socket: ""
  storage_address: ""
  storage_nat_address: ""
  storage_fstype: ""
  storage_mountpoint: ""
  storage_options: ""
oscied-transform2:
  verbose: "false"
  cleanup: "false"
  concurrency: 6
  rabbit_queues: "transform_private"
  mongo_connection: "mongodb://nodes:p09BPRYTaqKswzjT@192.168.0.5:27017/celery"
  rabbit_connection: "amqp://nodes:Pa0bQ2XFFftAoxlU@192.168.0.5:5672/celery"
  api_nat_socket: ""
  storage_address: ""
  storage_nat_address: ""
  storage_fstype: ""
  storage_mountpoint: ""
  storage_options: ""
oscied-webui:
  verbose: "false"
  cleanup: "false"
  max_upload_size: 4294967296
  max_execution_time: 180
  max_input_time: 600
  mysql_root_password: "DlO6FLn3kZsDikTD"
  mysql_user_password: "ZRpe5n9RTZd2F5oW"
  api_url: ""
  storage_address: "192.168.0.9"
  storage_nat_address: ""
  storage_fstype: "glusterfs"
  storage_mountpoint: "medias_volume_0"
  storage_options: ""
