default: PLEASE_DO_NOT_DESTROY_DEMO
environments:
  amazon:
    type: ec2
    access-key: AKIAIADEYC6IBHCMCTZQ
    secret-key: Vl5g/QLi********************************
    control-bucket: juju-****************.s3-website-us-east-1.amazonaws.com
    admin-secret: d29e6847c81a1e7441fa759134946594
    default-series: precise
    juju-origin: ppa
  maas:
    type: maas
    maas-server: http://10.10.10.1:80/MAAS
    maas-oauth: "2BAKqBZksMmpeWR3qt:VGDYJAuzYs8LLkcBse:9SreW2gyc5nvzXxPCaXc7mTR7wCdLUHp"
    admin-secret: super-secret-made-up-admin-key-1234
    default-series: precise
  local:
    type: local
    control-bucket: juju-a14dfaec23c4995999395c3830142d9a278
    admin-secret: 6608267b8c90b2a2949997934167bbd6b44
    data-dir: /home/famille/.juju/storage
    default-series: raring
    juju-origin: ppa
