orchestra:
  verbose: "false"
  root_secret: "t7LY8ZgQfv5Sb0Un"
  nodes_secret: "ilKkBr0xBC6gzumz"
  repositories_user: "oscied"
  repositories_pass: "aAvUFKMtvI35ZGUy"
  oscied_repository: "https://github.com/ebu/OSCIED/charms"
  mongo_admin_password: "zuT4NaKJRllxkWTA"
  mongo_nodes_password: "p09BPRYTaqKswzjT"
  rabbit_password: "Pa0bQ2XFFftAoxlU"
  storage_address: ""
  storage_nat_address: ""
  storage_fstype: ""
  storage_mountpoint: ""
  storage_options: ""
publisher1:
  verbose: "false"
  concurrency: 2
  rabbit_queues: "publisher_private"
  mod_streaming: "false"
  max_upload_size: 4294967296
  max_execution_time: 180
  max_input_time: 600
  mongo_connection: ""
  rabbit_connection: ""
  api_nat_socket: ""
  storage_address: ""
  storage_nat_address: ""
  storage_fstype: ""
  storage_mountpoint: ""
  storage_options: ""
publisher2:
  verbose: "false"
  concurrency: 2
  rabbit_queues: "publisher_private"
  mod_streaming: "false"
  max_upload_size: 4294967296
  max_execution_time: 180
  max_input_time: 600
  mongo_connection: ""
  rabbit_connection: ""
  api_nat_socket: ""
  storage_address: ""
  storage_nat_address: ""
  storage_fstype: ""
  storage_mountpoint: ""
  storage_options: ""
storage:
  verbose: "false"
  allowed_ips: "*"
  replica_count: 1
transform1:
  verbose: "false"
  concurrency: 6
  rabbit_queues: "transform_private"
  mongo_connection: ""
  rabbit_connection: ""
  api_nat_socket: ""
  storage_address: ""
  storage_nat_address: ""
  storage_fstype: ""
  storage_mountpoint: ""
  storage_options: ""
transform2:
  verbose: "false"
  concurrency: 6
  rabbit_queues: "transform_private"
  mongo_connection: ""
  rabbit_connection: ""
  api_nat_socket: ""
  storage_address: ""
  storage_nat_address: ""
  storage_fstype: ""
  storage_mountpoint: ""
  storage_options: ""
webui:
  verbose: "false"
  max_upload_size: 4294967296
  max_execution_time: 180
  max_input_time: 600
  mysql_root_password: "DlO6FLn3kZsDikTD"
  mysql_user_password: "ZRpe5n9RTZd2F5oW"
  api_url: ""
  storage_address: ""
  storage_nat_address: ""
  storage_fstype: ""
  storage_mountpoint: ""
  storage_options: ""
